name: flutter_woo
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1
environment:
  sdk: ^3.6.0


# app 图标
icons_launcher:
  image_path: "assets/icons/ic_logo.png"
  platforms:
    android:
      enable: true
      notification_image: "assets/icons/ic_foreground.png"
      # adaptive_background_color: '#ffffff'
      adaptive_background_image: "assets/icons/ic_background.png"
      adaptive_foreground_image: "assets/icons/ic_foreground.png"
    ios:
      enable: true

fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
# 启动图适配 android 11 及以下, 12 以上，IOS
flutter_native_splash:
  web: false
  color_android: "#ffffff"
  background_image_android: "assets/launcher/background.png"
  background_image_ios: "assets/launcher/background.png"
  image_ios: "assets/launcher/android.png"
  android_12:
    image: "assets/launcher/android12.png"
    icon_background_color: "#324ea1"



dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  package_info_plus: ^8.3.0
  shared_preferences: ^2.5.3
  dio: ^5.8.0+1
  adaptive_theme: ^3.7.0
  ducafe_ui_core: ^1.0.6
  cached_network_image: ^3.4.1
  flutter_svg: ^2.1.0
  carousel_slider: ^5.1.1
  validatorless: ^1.2.4
  pinput: ^5.0.1
  flutter_easyloading: ^3.0.5
  encrypt: ^5.0.3
  collection: ^1.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  icons_launcher: ^3.0.1
  flutter_native_splash: ^2.4.4
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
